### ISSUE TITLE
Rename to `clas12-qadb`?

### ISSUE THREAD

**Issue by c-dilks** [JeffersonLab/clas12-qadb#28]
To be more consistent with other CLAS12 repositories, shall we rename this one? Many other repositories follow the convention `clas12-[NAME]`, so we could have `clas12-qadb`. 

- [x] all old links will auto-redirect, so we don't expect this to be a breaking change for anyone, but consider making an announcement at least to the core developers
- [x] update documentation and code for any _common_ users, e.g. `clas12root`

**Comment by c-dilks** [comment]
@baltzell any showstoppers here, viz. in the `modulefiles`?

**Comment by baltzell** [comment]
> @baltzell any showstoppers here, viz. in the `modulefiles`?

No, should be fine, just do it and we'll deal with the fallout, if any.
